engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 200

exclude_paths:
- "**/__tests__/"
- "**/__mocks__/"
- "src/Reducers/reportResultReducer.js"
- "src/actions/listActions.js"
- "src/actions/reportResultActions.js"
- "src/components/InviteAgent.js"
- "src/components/PDFReport.js"
- "src/screens/startInspection/StartAlreadyInspectionedInspection.js"
- "src/components/InvitedCounselorsData.js"
- "src/screens/scheduleMeeting/ScheduleMeeting.js"
- "src/actions/counselorActions.js"
