merenda-merenda:
  build: .
  volumes:
    - .:/code
  privileged: true
  working_dir: /code
  net: host
  environment:
   - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    react-native run-android
    "
