android-emulator-merenda:
  build: .
  volumes:
    - .:/code
  privileged: true
  net: host
  environment:
   - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    cd /code/ && npm install
    /app/android-sdk-linux/tools/android list avd
    /app/android-sdk-linux/tools/emulator  -avd android-emulator & .
    sleep 2m && npm run android
    "
