merenda-merenda:
  build: .
  volumes:
    - /node_modules/
    - .:/code
    - /dev/bus/usb:/dev/bus/usb
  privileged: true
  working_dir: /code
  net: host
  ports:
    - "8081:8081"
  environment:
    - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    npm install --loglevel verbose
    adb reverse tcp:8081 tcp:8081
    echo 256 | tee -a /proc/sys/fs/inotify/max_user_instances
    echo 32768 | tee -a /proc/sys/fs/inotify/max_queued_events
    echo 65536 | tee -a /proc/sys/fs/inotify/max_user_watches
    react-native run-android
    "
