merenda-merenda:
  build: .
  volumes:
    - .:/code
  privileged: true
  working_dir: /code
  net: host
  environment:
   - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    npm install --loglevel verbose
    adb reverse tcp:8081 tcp:8081
    "
