merenda-merenda:
  build: .
  volumes:
    - .:/code
  privileged: true
  working_dir: /code
  net: host
  environment:
   - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    npm install --loglevel verbose
    adb reverse tcp:8081 tcp:8081
    /app/android-sdk-linux/tools/android list avd
    react-native run-android & .
    /app/android-sdk-linux/tools/emulator -avd emulator-android
    "
