android-emulator:
  build: .
  volumes:
    - .:/code
  privileged: true
  net: host
  environment:
   - DISPLAY=$DISPLAY 
  command: |
    bash -c "
    /app/android-sdk-linux/tools/android list avd
    /app/android-sdk-linux/tools/emulator  -avd android-emulator
    "